
# Generated by CodiumAI

import pytest

class TestBankAccount:

    # Deposit positive amount increases balance
    def test_deposit_positive_amount_increases_balance(self):
        account = BankAccount("John Doe", 100, True)
        account.deposit(50)
        assert account.balance == 152.5

    # Withdrawal decreases balance
    def test_withdrawal_decreases_balance(self):
        account = BankAccount("John Doe", 100, True)
        account.withdraw(50)
        assert account.balance == 47.5

    # Account information is returned correctly
    def test_account_information_is_returned_correctly(self):
        account = BankAccount("John Doe", 100, True)
        assert account.client() == "Account name: John Doe, balance: 100"

    # Deposit negative amount does not change balance
    def test_deposit_negative_amount_does_not_change_balance(self):
        account = BankAccount("John Doe", 100, True)
        account.deposit(-50)
        assert account.balance == 100

    # Withdrawal with insufficient funds does not change balance
    def test_withdrawal_with_insufficient_funds_does_not_change_balance(self):
        account = BankAccount("John Doe", 100, True)
        account.withdraw(150)
        assert account.balance == 100

    # Withdrawal with zero or negative amount does not change balance
    def test_withdrawal_with_zero_or_negative_amount_does_not_change_balance(self):
        account = BankAccount("John Doe", 100, True)
        account.withdraw(0)
        assert account.balance == 100